"""Qareen Intelligence Engine — Interface.

The intelligence engine is the core processing loop for operator utterances.
It classifies intent, assembles context from the ontology and vault, and
generates cards (structured proposals) for the operator.

Processing flow:
    1. process_utterance() — main entry point
    2. classify_intent() — Tier 0 regex, then Tier 1 local model
    3. assemble_context() — query ontology, QMD, work state
    4. generate_cards() — Tier 2 LLM call with assembled context

This file defines the interface only. Implementation lives in a
separate module to keep the contract clean.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .types import Card, ContextPacket, IntentResult

if TYPE_CHECKING:
    from ..ontology.model import Ontology


class IntelligenceEngine:
    """Processes natural-language utterances into structured cards.

    The engine operates in three tiers:
      - Tier 0: Regex/keyword matching (~2ms). Catches obvious intents
        like "add task" or "remind me".
      - Tier 1: Local model classification (~50ms). Uses a small
        on-device model for intent + entity extraction.
      - Tier 2: LLM generation (~500ms). Assembles full context and
        calls the LLM to generate cards.

    AMBIENT and FILLER intents short-circuit at Tier 0/1 and never
    reach Tier 2, saving latency and cost.
    """

    def __init__(self, ontology: Ontology, event_bus: object) -> None:
        """Initialize the intelligence engine.

        Args:
            ontology: The Qareen ontology instance for data access
                and relationship traversal.
            event_bus: The event bus for emitting card.generated and
                other intelligence events.
        """
        self._ontology = ontology
        self._event_bus = event_bus

    def process_utterance(self, text: str, session_id: str) -> list[Card]:
        """Process a natural-language utterance and generate cards.

        This is the main entry point. It runs the full pipeline:
        classify intent, assemble context, and generate cards.

        AMBIENT and FILLER intents return an empty card list without
        invoking Tier 2.

        Args:
            text: The raw utterance text from the operator.
            session_id: The current session id for transcript tracking.

        Returns:
            A list of Card instances (may be empty for low-signal
            utterances). Cards are in priority order.
        """
        raise NotImplementedError

    def classify_intent(self, text: str) -> IntentResult:
        """Classify the intent of an utterance.

        Runs Tier 0 (regex) first. If confidence is below threshold,
        falls through to Tier 1 (local model). The tier_used field
        in the result indicates which tier produced the classification.

        Args:
            text: The raw utterance text.

        Returns:
            An IntentResult with the classified intent, confidence,
            extracted entities, and the tier that was used.
        """
        raise NotImplementedError

    def assemble_context(self, intent: IntentResult) -> ContextPacket:
        """Assemble context for a Tier 2 LLM call.

        Queries the ontology for relevant people, projects, and tasks
        based on the extracted entities. Fetches vault context via QMD
        for recall-type intents. Pulls rolling transcript from the
        current session. Builds work state from active tasks.

        Each context field is budget-capped to prevent token overflow.
        The total_tokens field reflects the estimated sum.

        Args:
            intent: The classified intent with extracted entities.

        Returns:
            A ContextPacket with all assembled context fields populated
            and token counts estimated.
        """
        raise NotImplementedError

    def generate_cards(self, intent: IntentResult, context: ContextPacket) -> list[Card]:
        """Generate cards via a Tier 2 LLM call.

        Sends the assembled context and classified intent to the LLM.
        The LLM returns structured JSON which is parsed into typed
        Card instances.

        Args:
            intent: The classified intent result.
            context: The assembled context packet.

        Returns:
            A list of Card instances generated by the LLM. May be
            empty if the LLM determines no action is needed.
        """
        raise NotImplementedError
